### ISSUE TITLE
Thelio case has no labeling on audio I/O jacks

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#10]
Thelio case has no labeling on audio I/O jacks. This is an epic fail.  If I have to explain why, you should be ashamed of yourselves.

**Comment by magdesign** [comment]
At least a sketch to download where all ports are labeled so we can figure out which port is what.

**Comment by WatchMkr** [comment]
This is on the Thelio product roadmap.

**Comment by magdesign** [comment]
Here is the sketch of which plug is for what:

![system76_Thelio_Major_BackPanel](https://user-images.githubusercontent.com/5273166/69138935-e0840080-0abf-11ea-8d9b-1ac8871579f7.png)

found here on page 21: https://download.gigabyte.com/FileList/Manual/mb_manual_x399-designare-ex_e.pdf

**Comment by CaryHertert** [comment]
@jgrano can we call this closed?  or at least duplicated by #22  #23 #26 #28

**Comment by jgrano** [comment]
All new product releases are getting port labels.
