### ISSUE TITLE
Thelio case doesn't use a standard I/O cutout on the rear edge.

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#11]
This is not personally an issue for me.  But I've seen online comments by people who say it's a dealbreaker for them, and you should be aware of that.

**Comment by WatchMkr** [comment]
We won't be moving to a I/O shield.

**Comment by eric-s-raymond** [comment]
What's the advantage in the way it's done now?

Again, not a personal issue for me, but I am curious about the reasoning.

**Comment by WatchMkr** [comment]
In our view, I/O shields don't match with the rest of the system and are best suited for generic off-the-shelf PC cases rather than a complete product.

**Comment by eric-s-raymond** [comment]
I think you have dismissed this issue too quickly.

Part what serious technical buyers are looking for when they acquire a high-end system like this is a certain degree of future-proofness; they want to know that they're going to be able to service and upgrade  it whether or not the vendor is there to help.

Such users put less value on what you think of as a "complete product" positioned like consumer electronics and more on the chassis as the base for a portfolio of options.  Not using a standard cutout is a signal that you don't share this concern.  It clashes with the philosophy of open source and modularity you have expressed elsewhere.

I'm trying to put together an issue addressing a related and slightly larger problem: it seems to me that the Thelio's design reveals a somewhat confused product strategy. I'll have more to say about this when I think I can give crisp and actionable advice.
