### ISSUE TITLE
Thelio case ports need visual contrast so they can be found in dim light.

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#12]
Black port openings on a black case may appeal to skinny-jeans hipster designers by tickling their ooh-minimalism response, but functionally they suck.  Have mercy on people trying to plug in cables in dim light and cramped spaces.

Silk-screen white outlines around the damn things! Either that or make your port panel(s) out of metal with a finish that is *not black*. Visual contrast is everybody's friend here.

**Comment by WatchMkr** [comment]
This is on the product roadmap.
