### ISSUE TITLE
Thelio connector pins for the front button are too fragile

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#14]
Related to #6.  I had a buddy who troubleshoots industrial computers for a living assist me in getting the case top back on the Thelio, because I couldn't.  He poked around it a bit and said "Here's part of your problem" and then temporarily removed the part so I could photograph it.

https://photos.google.com/photo/AF1QipO0v9uXa0A30XOwsFC5C_b6ZmDwUw3SuV9XHU9b

Note the bent pins.  It's obvious what happened; during one or more of my futile, profanity-laden attempts to refit the case top, they were misaligned and got mashed. My friend straightened then with a needlenose.

His verdict "Somebody got too cute." He thinks that should have been done with a conventional cable and a plug, rather than making the mating of the connector halves rigidly dependent on the alignment of the case top when it's pushed down - that was just asking for the failure mode presented at the image link.  I agree.

In my opinion as an experienced PC builder myself, altogether too much of this case design needs to be shot and buried under a gravestone labeled "Somebody got too cute". Some of the ideas are really good, like the custom vertical drive cage.    Some  are insubstantial but fun, like the encoding of the Unix epoch in the rear fan grille.  But there's too much about it that smacks of designers doing things because they could, without pondering whether they should.

Please think harder about serviceability and minimizing avoidable mechanical failure modes next time.

**Comment by WatchMkr** [comment]
Thanks for providing your opinion. We appreciate the feedback.
