### ISSUE TITLE
Thelio case quality after one year of usage

### ISSUE THREAD

**Issue by magdesign** [system76/thelio#15]
This is meant as constructive feedback!

After one year of usage  my Thelio case is loosing its shape.
The wooden foil starts to get blisters and the edges start to bend upwards.

![DSC01640](https://user-images.githubusercontent.com/5273166/69132181-e7a51180-0ab3-11ea-9ef0-32a67c96d252.JPG)
![DSC01639](https://user-images.githubusercontent.com/5273166/69132196-ec69c580-0ab3-11ea-88cc-1c6bd45fc58c.JPG)
![DSC01638](https://user-images.githubusercontent.com/5273166/69132207-effd4c80-0ab3-11ea-91d6-b278ff74aad3.JPG)

You should seriously think about material thickness, quality check and have some talks with people who work with metal parts every day (the ones who get dirty hands). Then bring an updated version of the case and maybe some ideas for us to fix some issues.

As soon as I have more spare time, I will start upgrading my Thelio case to be much more quit since the noise level is still the biggest issue..... will post my progress here...

**Comment by WatchMkr** [comment]
Thanks for the feedback! We have made a large number of changes in both process and design for exactly these things that we've seen. If you'll please reach out to customer support, we'll be happy to exchange your exterior.

Regarding the noise level, last Friday we shipped a software update that reduced the audible fan noise by 7 decibels. The update is to a software package called system76-power. Are you running Pop or Ubuntu? Have you made any changes to the wiring in the case?

You can check the check the system76-power version with the following command (version ending with 1a6e703 has the update):

pop@pop-os:~$ apt-cache policy system76-power
system76-power:
  Installed: 1.0.1~1573832218~19.10~1a6e703
  Candidate: 1.0.1~1573832218~19.10~1a6e703
  Version table:
 *** 1.0.1~1573832218~19.10~1a6e703 1001

**Comment by magdesign** [comment]
Running Pop-os 18.04 LTS 
checked the system76-power version:
`system76-power is already the newest version (1.0.1~1570998296~18.04~d0013c0)`
Is 1a6e703 only available for 19.10 users ?

I might come back to your offer for a case replacement, thanks!

**Comment by WatchMkr** [comment]
We're backporting the new fan curves to Pop!_OS 18.04 now. You should see the update by the end of the week.

**Comment by WatchMkr** [comment]
The new fan curves have been released in Pop 18.04. Run updates and check for version `system76-power_1.0.1~1574207757~18.04~4f6a818` with the command `apt-cache policy system76-power`.

You should notice a considerable difference.

Again, thank you for the feedback. We are pretty confident we've addressed both the veneer adhering and case rigidity with updates over the past year. I'm going to go ahead and close the issue for now.

**Comment by magdesign** [comment]
The new curves are amazing, great work!
