### ISSUE TITLE
https://thel.io/ Link in description is dead

### ISSUE THREAD

**Issue by magdesign** [system76/thelio#16]

**Comment by brs17** [comment]
That page has been moved to be accessible from the [showcase page](https://system76.com/showcase) and can be reached directly at https://thelio.origin76.com/

**Comment by magdesign** [comment]
Just wanted to point out that in this Github repo, just under the title you still have the link:
Thelio Desktop by System76 https://thel.io/

**Comment by brs17** [comment]
> Just wanted to point out that in this Github repo, just under the title you still have the link:
> Thelio Desktop by System76 https://thel.io/

Ah, good catch. @btkostner said we do want that to direct to system76.com/desktops so I will get this on the web team's radar. Thank you!

**Comment by jgrano** [comment]
Fixed. Closing.
