### ISSUE TITLE
New top case brace 

### ISSUE THREAD

**Issue by jgrano** [system76/thelio#20]
Move R&D thelio top case brace into a productive task.

**Comment by jgrano** [comment]
Working on rough design 7/8/21

**Comment by jgrano** [comment]
Design has been made.  
Ready for review & modification. 

https://a360.co/3hVGjaE

**Comment by CCooper20** [comment]
Main alumn. plate has been machined and welded brackets (7/19/21)
Waiting on new 1/4" reamer to loosen up bracket pin holes (tight fit now)
Wed (7/21/21) will machine out tapped brackets (need to program and machine)

@jgrano do we need to create a WI for this fixture? 

@jgrano / @CaryHertert And adding a check box for when you get the parts to etch ID on brackets.

- [ ] Etch welded brackets with ID
- [ ] Etch tapped brackets with ID

**Comment by jgrano** [comment]
@CCooper20 we should make a WI for this after we have flushed it out. Being that we're still heavily in the R&D setup here I think it will likely change before we get done. 

I like the check mark feature for the etching.
