### ISSUE TITLE
CPU Duct - Move fan down 5mm for thermal testing

### ISSUE THREAD

**Issue by jgrano** [system76/thelio#21]
THEALU-010010 -- seems to work based on Levi's initial testing. Needs mfg refinements.

**Comment by CaryHertert** [comment]
@jgrano can you help clarify this task?  is this fan and duct and back panel vent?

**Comment by jgrano** [comment]
@CaryHertert Part THEALU-010010 is in ThelioV2, material is regretfully mis-assigned as 0.63" and I cannot quickly change to 1.6mm standard material. The profile either needs to be rebuilt or THEALU-010009 needs to change.
