### ISSUE TITLE
Replace Rivnuts, perhaps with pemcerts.

### ISSUE THREAD

**Issue by jgrano** [system76/thelio#29]
Need more info

**Comment by jgrano** [comment]
@CaryHertert please add the email quote info

**Comment by CaryHertert** [comment]
[PEMEdge CSI.pdf](https://github.com/system76/thelio/files/6788567/PEMEdge.CSI.pdf)
[PEMEdge lab services.pdf](https://github.com/system76/thelio/files/6788568/PEMEdge.lab.services.pdf)
[Line Card.pdf](https://github.com/system76/thelio/files/6788569/Line.Card.pdf)

**Comment by jgrano** [comment]
@CaryHertert Can we look at finding a few standard parts (m3 nut inserts etc..) that we can push out to sourcing? I think we need to run through a few more samples and get an order together for ~50k of each from China.
