### ISSUE TITLE
Fan connectors to improve duct installation and removal

### ISSUE THREAD

**Issue by CaryHertert** [system76/thelio#53]
Fan connectors to improve duct installation and removal. Thelio Io fan headers plug into connectors near the duct. Fans on the duct plug into the opposite connector. Installing the duct connects the fans to the Thelio Io. Needs to be modular to grow from one fan to six. (per carl)

**Comment by CaryHertert** [comment]
@WatchMkr I am picturing the fans (1-6) loaded in to the duct and the assembly installed in to the machine as a unit.  Will the fan/duct assembly be connected to the IO via board to board connector or wire?

**Comment by leviport** [comment]
Now that the two CPU fans connect to the small splitter board, I believe this issue is solved
