### ISSUE TITLE
Thelio case top is way too hard to put back on once removed.

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#6]
This is my single worst problem with the Thelio case.  I had to remove the case top to clear a cable that had shifted into an unfortunate collision with a fan blade, and despite many tries and much cursing have not succeeded in getting it reassembled.

Take this seriously, please. I've been tinkering with PCs and their cases since the early 1980s and I have *never before* seen one that was this much of a revolving bitch to put together.  Seems like it requires some combination of secret black magic and the dexterity of a neurosurgeon.

I've been running the machine caseless for days now and this is not good.  My office is dusty and without a case and good filters conductive dust *will* eventually get somewhere that will crash it.  (I used to see this happen occasionally with the Thelio's predecessor.)

This problem is serious enough that I am contemplating transplanting the Thelio's guts into my old case to banish it.

I don't have any clear idea how to fix this.

**Comment by WatchMkr** [comment]
Thanks for your input. There are certainly ways we can make that an easier experience.

**Comment by eric-s-raymond** [comment]
Maybe start with a YouTube video explaining the black magic?

I'm going to wrestle with the fscker some more later today.

**Comment by brs17** [comment]
@eric-s-raymond guides/videos for working on Thelio can be found here: https://system76.com/guides

**Comment by eric-s-raymond** [comment]
I see links for three Thelio variants there.  How do I tell which one mine is?

**Comment by WatchMkr** [comment]
There is a badge on the back of the computer with your model number.
