### ISSUE TITLE
Thelio case lacks front- or top-mounted USB ports.

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#9]
Lack of front- or top-mounted USB ports is annoying.

You may not think this is a big deal, but I use a very common Logitech trackball called an m570, a wireless device with a USB radio dongle. It can matter a lot whether that device is on the front, top, or back of the machine, because the low-power radio transceiver has trouble if it's too far away from or not in LOS with the trackball.

You're competing with cases that have  this. It's pretty much a checklist feature for the high-end ones these days; you shouldn't get left behind.

**Comment by WatchMkr** [comment]
Front ports are on the product roadmap.

**Comment by michalsapka** [comment]
Was this abandoned in the redesign process?

**Comment by leviport** [comment]
Front (well, top-front) ports have been added in the latest iteration of the Thelio/Nebula designs: https://github.com/system76/thelio/pull/59
